### ISSUE TITLE
Color previews?

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#74] opened 2015-06-20 16:20 UTC
Does Peppermint have a plugin I've missed to preview the CSS color defined? Something like:

https://github.com/abe33/atom-color-highlight

**Comment by osxpeppermint** [comment] 2015-06-21 08:46
Well, this is very interesting. Never thought of it - but I believe I can find some way of implementing it (preferable as part of a Builtin...)

**Comment by osxpeppermint** [comment] 2015-06-29 12:36
Closed as duplicate of https://github.com/osxpeppermint/peppermint/issues/84

**Closed by osxpeppermint** 2015-06-29 12:36 UTC
Labels: feature request, plugin
