### ISSUE TITLE
Xdebug plugin

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#75] opened 2015-06-20 16:21 UTC
Peppermint could really use an Xdebug plugin to make PHP development easier. here's an example:

https://github.com/spocke/php-debugger

**Comment by osxpeppermint** [comment] 2015-06-21 08:47
Yep, I know about Xdebug and comes really handy when talking about PHP development - so it already is in my to-do list... ;)

**Comment by osxpeppermint** [comment] 2015-06-29 15:36
Closed as a duplicate of https://github.com/osxpeppermint/peppermint/issues/83

**Closed by osxpeppermint** 2015-06-29 15:36 UTC
Labels: feature request, plugin
