### ISSUE TITLE
EditorConfig?

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#72] opened 2015-06-20 13:53 UTC
Does Peppermint respect `.editorconfig` settings?

**Comment by osxpeppermint** [comment] 2015-06-20 14:02
Closed as a duplicate of: https://github.com/osxpeppermint/peppermint/issues/15

P.S. Unfortunately I haven't implemented yet. Although (inside info), the last few days I did integrate editorconfig support. It's that I haven't made it to fully integrate it yet (and thus, make use of it). But it shouldn't take that long. :)

**Closed by osxpeppermint** 2015-06-20 14:02 UTC
Labels: duplicate
