### ISSUE TITLE
Create new window

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#63] opened 2015-06-18 23:55 UTC
I'd like to be able to open multiple windows.

**Comment by osxpeppermint** [comment] 2015-06-19 11:50
Well, this is an interesting suggestion - and I know it's missing.

However, since it'll require some more... core tweaks, I'm leaving it in the to-do queue until more critical things are resolved. :)

**Comment by bobrocke** [comment] 2015-06-19 20:29
OK. But a Mac app that can't do multiple windows is an odd Mac app.

**Comment by osxpeppermint** [comment] 2015-06-20 09:39
You do have a point...

**Comment by osxpeppermint** [comment] 2015-07-02 12:15
Closed as a duplicate of https://github.com/osxpeppermint/peppermint/issues/85

**Closed by osxpeppermint** 2015-07-02 12:15 UTC
Labels: feature request
